#!/bin/bash
# # Copyright 2010: Sindre Røkenes Myren | smyrman -at- gmail -dot- com
# This program, Gitsy, is release under the GPL2 Licencs. See the file COPYING
# for more information.

source $HOME/.gitsyrc


## Main switch case (argument check) ##
case $1 in
# Print help and exit
help)
	echo -e "USAGE:\n  gitsy COMMAND"

	echo -e "\nCOMMANDS:"
	echo -e "  help        show this text"
	echo -e "  status      Show a sumary og all changes done so far"
	echo -e "  sync        Add any changes, then issue git pull followed by git push."
	echo -e "  pull        pull all changes from remote host"
	echo -e "  push        add and commit all changes, then push to remote host"

	echo -e "\nNOTE: Gitsy commands are NOT affected by the \$PWD!"
	echo -e "For the init command, note that REPO must be the name of a"\
	        "folder in your home directory. To add folders outside your"\
	        "home dir, see the README."
	exit
;;

# Add an commit all changes, then push master to origin/master (all repos)
push)
	for repo in ${REPOS[@]}; do
		echo -e "\n\e[1;32m## Repository located at '$HOME/$repo' ##\e[m"
		cd $HOME/$repo && git add . && git commit -a -m "autocommit on $(date)"
		cd $HOME/$repo && git push origin master
	done
;;

# pull from origin/master (all repos)
pull)
	for repo in ${REPOS[@]}; do
		echo -e "\n\e[1;32m## Repository located at '$HOME/$repo' ##\e[m"
		cd $HOME/$repo && git pull origin master
	done
;;

# pull AND push from/to origin/master (all repos)
sync)
	for repo in ${REPOS[@]}; do
		echo -e "\n\e[1;32m## Repository located at '$HOME/$repo' ##\e[m"
		cd $HOME/$repo && git add . && git commit -a -m "autocommit on $(date)"\
		cd $HOME/$repo && git pull origin master
		cd $HOME/$repo && git push origin master
	done
;;

# show git status for all repos
status)
	for repo in ${REPOS[@]}; do
		echo -e "\n\e[1;32m## Repository located at '$HOME/$repo' ##\e[m"
		cd $HOME/$repo && git status
	done
;;
esac
